dist: focal
language: node_js
addons:
        hosts:
                - example.com

env: NODE_GYP_FORCE_PYTHON=python3 EXPERIMENTAL_NODE_GYP_PYTHON3=1
before_install:
        - sudo debconf-set-selections < tests/debconf.txt
        - sudo mkdir -p /etc/selfhost/apps
        - sudo cp tests/selfhost_app.yml /etc/selfhost/apps/thunderhub-regtest.conf
        - gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 3D9E81D3CA76CDCBE768C4B4DC6B4F8E60B8CF4C
        - gpg --export 3D9E81D3CA76CDCBE768C4B4DC6B4F8E60B8CF4C | sudo apt-key add -
        - echo 'deb https://deb.ln-ask.me/beta buster common local desktop' | sudo tee /etc/apt/sources.list.d/cryptoanarchy.list > /dev/null
        - sudo apt-get update
        - sudo apt-get install --no-install-recommends selfhost-clearnet
        - sudo apt-get install python3-lnpbp-testkit python3-selenium libnode-dev
        - sudo usermod -a -G lnd-system-regtest,bitcoin-regtest $USER

script: tests/travis.sh
