dist: bionic
language: node_js
addons:
        hosts:
                - example.com

before_install:
        - sudo debconf-set-selections < tests/debconf.txt
        - sudo cp tests/selfhost_app.yml /etc/selfhost/apps/thunderhub-regtest.conf
        - gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 3D9E81D3CA76CDCBE768C4B4DC6B4F8E60B8CF4C
        - gpg --export 3D9E81D3CA76CDCBE768C4B4DC6B4F8E60B8CF4C | sudo apt-key add -
        - echo 'deb https://deb.ln-ask.me/beta buster common local desktop' | sudo tee /etc/apt/sources.list.d/cryptoanarchy.list > /dev/null
        - sudo apt update
        - sudo apt install --no-recommends selfhost-clearnet
        - sudo apt install python3-lnpbp-testkit python3-selenium libnode-dev
        - sudo useradd -a -G lnd-system-regtest,bitcoin-regtest $USER

script: tests/travis.sh
